Assignment4/my-ra-app/backend/musicrater/urls.py
from django.urls import include, path
from . import views
from rest_framework import routers

app_name = 'musicrater'

urlpatterns = [
    path('', views.index, name='index'),
    
    # add a new rating 
    # post request
    # returns {status:<'ok' if rating added or 'rating exists' if rating is already in db>}
    path('add-rating/<str:song>/<str:artist>/<int:rating>/<str:user>', views.AddRating.as_view(), name='views.AddRating.as_view()'),

    # edit a rating
    path('edit/<int:key>/<str:song>/<str:artist>/<int:rating>', views.Edit.as_view(), name='views.Edit.as_view()'),

    # delete rating
    # delete request
    # returns {status:<'ok' if song edited deleted>}
    path('delete-rating/<int:key>', views.DeleteRating.as_view(), name='views.DeleteRating.as_view()'),

    #get users ratings
    #get request 
    #returns {ratings:[(song: <song name> ,artist: <song's artist>,rating:<user's rating>, id: <primary_key for rating>, user: <user>},...]}
    path('user-ratings/<str:user>', views.UserRatings.as_view(), name='views.UserRatings.as_view()'),

    #get summary ratings for all songs (for social tab)
    #get request
    # returns {ratings:[(song: <song name> ,artist: <song's artist>, average: <average rating of song for all users>},...]}
    path('summary-all-ratings', views.SummaryRatings.as_view(), name='views.SummayRatings.as_view()'),

    
]

Assignment4/my-ra-app/backend/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('rater/',include('musicrater.urls')),
]

Assignment4/my-ra-app/backend/musicrater/models.py
from django.db import models

class Ratings(models.Model):
    id = models.AutoField(primary_key=True)
    artist= models.CharField(max_length=100)
    user = models.CharField(max_length=100)
    rating = models.IntegerField()
    song = models.CharField(max_length=100)
    class Meta:
        verbose_name_plural = "Ratings"
    def __str__(self):
        return (self.user + " gave " + self.song+ " a " + str(self.rating))
    
    
    
    
    

Assignment4/my-ra-app/backend/musicrater/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse
from .models import Ratings
from requests import post, get
from rest_framework.views import APIView
from .credentials import REDIRECT_URI, CLIENT_SECRET, CLIENT_ID
from rest_framework.response import Response
from rest_framework import status

def index(request):
    return render(request, '../frontendbuild/index.html')

# add a new rating 
# returns {status:<'ok' if rating added or 'rating exists' if rating is already in db>}
class AddRating(APIView):
    def post(self, request, song, artist, rating, user):
        exists=Ratings.objects.filter(song=song).filter(user=user).exists()
        print(song,artist,rating,user)
        if exists: return Response({"status":'rating exists'}, status=status.HTTP_200_OK)
        if not (rating<=5 and rating>0): return Response({"status":'invalid rating'}, status=status.HTTP_200_OK)
        else:
            r=Ratings()
            r.artist=artist
            r.song=song
            r.rating=rating
            r.user=user
            r.save()
            return Response({"status":'ok'}, status=status.HTTP_200_OK)

# # edit a rating
# # {status:<'ok' if rating edited>
# class EditRating(APIView):
#     def put(self, request, key, newRating):
#         rating=Ratings.objects.get(id=key)
#         rating.rating=newRating
#         return Response({status:'ok'}, status=status.HTTP_200_OK)

# modify the song of a rating
# returns {status:<'ok' if song edited or 'rating exists' if the user has already rated a song with the new song and new artist>}
class Edit(APIView):
    def put(self, request, key, artist, song, rating):
        nr=rating
        rating=Ratings.objects.get(id=key)
        if(rating.artist==artist and rating.song==song):
            rating.rating=nr
            rating.save()
            print(rating)
            return Response({'status':'ok'}, status=status.HTTP_200_OK)
        else:
            exists=Ratings.objects.filter(song=song).filter(user=rating.user).filter(artist=artist).exists()
            if exists: return Response({'status':'rating exists'}, status=status.HTTP_200_OK)
            else:
                rating.rating=nr
                rating.song=song
                rating.artist=artist
                rating.save()
                return Response({'status':'ok'}, status=status.HTTP_200_OK)

# delete rating
# returns {status:<'ok' if song edited deleted>}
class DeleteRating(APIView):
    def delete(self, request, key):
        rating=Ratings.objects.get(id=key)
        rating.delete()
        return Response({'status': 'ok'}, status=status.HTTP_200_OK)
    


#get users ratings
# returns {ratings:[(song: <song name> ,artist: <song's artist>,rating:<user's rating>, key: <primary_key for rating>, user: <user>},...]}
class UserRatings(APIView):
    def get(self, request, user):
        ratings= Ratings.objects.filter(user=user).values()
        return Response({'ratings':ratings}, status=status.HTTP_200_OK)

#get summary ratings for all songs
# returns {ratings:[(song: <song name> ,artist: <song's artist>, average: <average rating of song for all users>},...]}
class SummaryRatings(APIView):
    def getAvgRating(self,song, artist):
        avg=0
        ratings=Ratings.objects.filter(song=song).filter(artist=artist)
        count=ratings.count()
        if not count: return None
        for r in ratings:
            avg+=(1/count)* r.rating
        return avg
        
    def get(self, request):
        res=[]
        songs=Ratings.objects.values("song").distinct().values("song")
        print(songs)
        for song in songs:
            artists=Ratings.objects.filter(song=song['song']).values("artist").distinct()
            for artist in artists: 
                res.append({
                    'song': song['song'],
                    'artist': artist['artist'],
                    'average': self.getAvgRating(song['song'], artist['artist']),
                })
        return Response(res, status=status.HTTP_200_OK)

Assignment4/my-ra-app/backend/musicrater/templates/musicrater/index.html
<!DOCTYPE html>
<html lang="en">
	<body>
		{% load static %}
		<link
			rel="stylesheet"
			type="text/css"
			href="{% static 'musicrater/style.css' %}"
		/>
		<div class="h-center v-center">
			<h1>music-db</h1>
			<h2>Registration</h2>
			<div>
				<form action="{% url 'musicrater:register' %}" method="POST">
					{% csrf_token %}
					<label for="name">Username:</label>
					<input type="text" id="username1" name="name" /><br />

					<label for="pwd">Password:</label>
					<input type="text" id="password" name="pwd" /><br />
					{% if error_message %}
					<p><strong>{{ error_message }}</strong></p>
					{% endif %}
					<input
						class="button black-text-bg white-text"
						type="submit"
						value="Register"
						name="Register"
					/>
				</form>
			</div>
			<h2>Retrieve Songs By Username</h2>
			<div>
				<form action="{% url 'musicrater:retrieve' %}" method="POST">
					{% csrf_token %}
					<label for="name">Username:</label>
					<input type="text" id="user-ret" name="name" /><br />
					<input
						class="button black-text-bg white-text"
						type="submit"
						value="Retrieve"
						name="retRating"
					/>
				</form>
				{% if user_reviews %}
				<p>{{ usr }}'s review:</p>
				{% for review in user_reviews %} {{ review.song.song }} -> {{ review.rating }} <br />
				{% endfor %} {% else %}
				<p>{{ review_err_msg }}</p>
				{% endif %}
			</div>

			<h2>Find Songs By Emoji</h2>
			<div>
				<form action="{% url 'musicrater:retrieveByEmoji' %}" method="POST">
					{% csrf_token %}
					<input class="button emoji" type="submit" value="😁" name="emoji" />
					<input class="button emoji" type="submit" value="🥳" name="emoji" />
					<input class="button emoji" type="submit" value="🥺" name="emoji" />
				</form>
				<div style="padding-bottom: 5vh">
					{% if emoji_report %}
					<p>Songs rated with {{ emoji }}:</p>
					{% for song, per in emoji_report.items %} {{ song}} -> {{per}}
					<br />
					{% endfor %} {% endif %}
				</div>
			</div>
		</div>
	</body>
</html>

Assignment4/my-ra-app/backend/musicrater/templates/musicrater/login_failed.html
<!DOCTYPE html>
<html lang="en">

<body>
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'musicrater/style.css' %}" />
	<div class="h-center v-center">
		Login Unsuccessful. <br>
		Please login with the credentials we provide. <br>
		Click <a href="https://www.spotify.com/logout/" target="_blank">here</a> to logout from this Spotify
		account.<br>
		We will redirect you back to our app in <span id="second">7</span> seconds.
	</div>
	<script>

		let timeleft = 6;
		setInterval(function () {
			if (timeleft <= 0) {
				clearInterval(downloadTimer);
				document.getElementById("second").innerHTML = "0";
			} else {
				document.getElementById("second").innerHTML = timeleft;
			}
			timeleft -= 1;
		}, 1000);

		function redirect() {
			window.location.href = "http://localhost:3000/";
		}
		setTimeout(redirect, 8000);

	</script>
</body>

</html>

Assignment4/my-ra-app/backend/musicrater/templates/musicrater/reg_succ.html
<!DOCTYPE html>
<html lang="en">
	<body>
		{% load static %}
		<link
			rel="stylesheet"
			type="text/css"
			href="{% static 'musicrater/style.css' %}"
		/>
		<div class="h-center v-center">
				Registration Successful! <br>
				Redirecting you...
		</div>
		<script>
    function redirect(){
       window.location.href = "{% url 'musicrater:index' %}";
    }

    setTimeout(redirect, 1250);
</script>
	</body>
</html>